openapi: 3.0.3
info:
  title: Spring Sample App API
  description: API pour l'application spring-sample
  version: '1.0'
servers:
  - url: localhost
paths:
  /api/v1/boat:
    get:
      summary: "Récupération d'un bateau via son nom"
      operationId: get_boat
      tags:
        - Boat
      parameters:
        - in: query
          name: boatName
          required: true
          description: "Nom du bateau à récupérer"
          schema:
            type: string
      responses:
        '200':
          description: "Information du bateau demandée"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Boat'
        '400':
          description: "Fonctional Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: "Enregistrement d'un nouveau bateau"
      operationId: post_boat
      tags:
        - Boat
      requestBody:
        description: "Information du bateau à enregistrer"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Boat'
      responses:
        '201':
          description: "Création du bateau OK"
        '400':
          description: "Fonctional Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: "Boat Already Exist"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: "Mise à jour des informations d'un bateau"
      operationId: put_boat
      tags:
        - Boat
      requestBody:
        description: "Information du bateau à modifier"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Boat'
      responses:
        '204':
          description: "Mise à jour du bateau OK"
        '400':
          description: "Fonctional Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: "Suppression d'un bateau via son nom"
      operationId: delete_boat
      tags:
        - Boat
      parameters:
        - in: query
          name: boatName
          required: true
          description: "Nom du bateau à supprimer"
          schema:
            type: string
      responses:
        '204':
          description: "Suppression du bateau OK"
        '400':
          description: "Fonctional Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/boat/img:
    get:
      summary: "Récupération de l'image du bateau via son nom"
      operationId: get_boat_image
      tags:
        - Boat
      parameters:
        - in: query
          name: boatName
          required: true
          description: "Nom du bateau à récupérer"
          schema:
            type: string
      responses:
        '200':
          description: "Image du bateau demandée"
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: "Fonctional Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Boat:
      type: object
      title: Boat
      description: "Objet représentant un bateau"
      properties:
        name:
          description: "Nom du bateau"
          type: string
        description:
          description: "Description textuelle du bateau"
          type: string
    Error:
      type: object
      title: Error
      description: "Objet generique pour les retours en erreur"
      required:
        - status
        - message
      properties:
        status:
          type: integer
          description: "Code statut HTTP"
        message:
          type: string
          description: "Une description de l'erreur"
